language: python
cache: pip
python:
  - "2.7"
install:
  - pip install nose coveralls
  - pip install -r requirements.txt
script: nosetests --nologcapture --with-coverage --cover-package=cloudarmy
after_success:
    coveralls
